# Generated by Django 6.0 on 2025-12-10 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-created_at'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterModelOptions(
            name='share',
            options={'ordering': ['-created_at'], 'verbose_name': 'Share', 'verbose_name_plural': 'Shares'},
        ),
        migrations.AddField(
            model_name='file',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the file was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this file is marked as favorite'),
        ),
        migrations.AddField(
            model_name='file',
            name='last_accessed',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Last time the file was accessed/viewed', null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, help_text='MIME type of the file', max_length=100),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AddField(
            model_name='folder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the folder was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this folder is marked as favorite'),
        ),
        migrations.AddField(
            model_name='share',
            name='access_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this share has been accessed'),
        ),
        migrations.AddField(
            model_name='share',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this share is currently active'),
        ),
        migrations.AddField(
            model_name='share',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(help_text='The actual file', upload_to='files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Folder containing this file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the file', max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the file', on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the folder', max_length=255),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(help_text='Owner of the folder', on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent folder, if this is a subfolder', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='core.folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated'),
        ),
        migrations.AlterField(
            model_name='share',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created'),
        ),
        migrations.AlterField(
            model_name='share',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this share link expires', null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='file',
            field=models.ForeignKey(blank=True, help_text='File being shared', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.file'),
        ),
        migrations.AlterField(
            model_name='share',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Folder being shared', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='core.folder'),
        ),
        migrations.AlterField(
            model_name='share',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique share identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='share',
            name='password',
            field=models.CharField(blank=True, help_text='Optional password to access the share', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='share',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Specific users who can access this share', related_name='shared_with_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'folder'], name='core_file_owner_i_b4b109_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'created_at'], name='core_file_owner_i_c1e274_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'parent'], name='core_folder_owner_i_90d78f_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['owner', 'created_at'], name='core_folder_owner_i_93a912_idx'),
        ),
        migrations.AddIndex(
            model_name='share',
            index=models.Index(fields=['is_active', 'expires_at'], name='core_share_is_acti_8d2aad_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('owner', 'parent', 'name'), name='unique_folder_name_per_parent'),
        ),
    ]
